#  ----------------------------------------------------
#  AutoMessage Configuration File
#  ----------------------------------------------------
#  Message Configuration:
#     Messages are handled in lists to allow for advanced customization!
#     Feel free to add color codes by using & in your messages!
#     To split a message onto multiple lines use the %n delimiter!
#     Lines starting with / will be run as a command!
#     To add single apostrophes into a message use ''.
#     For a complete tutorial go to http://dev.bukkit.org/server-mods/automessage.
#     If you are unfamiliar with YAML use the in-game commands: /am help

settings:
  enabled: true
  min-players: 0
  log-to-console: false
message-lists:
  formatted:
    enabled: true
    interval: 45
    expiry: -1
    random: false
    prefix: ''
    suffix: ''
    messages:
    - '%6s %9s %10s':
      - Custom
      - formatted
      - '&2message!'
  regular:
    enabled: true
    interval: 45
    expiry: -1
    random: false
    prefix: '[&bPrefix&r] '
    suffix: ' [&4Suffix&r]'
    messages:
    - '&1First&r message %nin the default list!': []
    - '&2Second&r message %nin the default list!': []
    - '&3Third&r message %nin the default list!': []
    - These messages will be displayed to users with %nautomessage.receive.default!: []
