multiserver:
  use-netevents: true
permissions:
  debug: true
  allowOps: false
  user-add-groups-last: false
  log-players: false
  createUserRecords: false
  backend: file
  informplayers:
    changes: false
  backends:
    file:
      type: file
      file: groups.yml
updater: true
alwaysUpdate: false
